<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Scriban" Version="6.4.0" />
    <PackageReference Include="SimpleInjector" Version="5.5.0" />
    <PackageReference Include="System.IO.Abstractions" Version="22.1.0" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RepoM.ActionMenu.Interface\RepoM.ActionMenu.Interface.csproj" />
    <ProjectReference Include="..\RepoM.Api\RepoM.Api.csproj" />
  </ItemGroup>

</Project>
