//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System;

namespace RepoM.ActionMenu.Core.Model.Functions
{
    partial class FileFunctions
    {
        protected sealed override void RegisterFunctions()
        {
            RegisterFunction("find_files", (Func<RepoM.ActionMenu.Core.Model.ActionMenuGenerationContext, Scriban.Parsing.SourceSpan, string, string, string[]>)FindFiles);
            RegisterFunction("file_exists", (Func<RepoM.ActionMenu.Core.Model.ActionMenuGenerationContext, string, bool>)FileExists);
            RegisterFunction("dir_exists", (Func<RepoM.ActionMenu.Core.Model.ActionMenuGenerationContext, string, bool>)DirectoryExists);
        }
    }
}

namespace RepoM.ActionMenu.Core.Model.Functions
{
    partial class RepositoryFunctions
    {
        protected sealed override void RegisterFunctions()
        {
            RegisterConstant("name", Name);
            RegisterConstant("path", Path);
            RegisterConstant("safe_path", SafePath);
            RegisterConstant("location", Location);
            RegisterConstant("branch", CurrentBranch);
            RegisterConstant("branches", Branches);
            RegisterConstant("local_branches", LocalBranches);
            RegisterConstant("remotes", Remotes);
        }
    }
}

namespace RepoM.ActionMenu.Core.Model.Functions
{
    partial class WebFunctions
    {
        protected sealed override void RegisterFunctions()
        {
            RegisterFunction("url_encode", (Func<string, string>)UrlEncode);
            RegisterFunction("url_decode", (Func<string, string>)UrlDecode);
            RegisterFunction("url_escape", (Func<string, string>)UrlEscape);
            RegisterFunction("html_encode", (Func<string, string>)HtmlEncode);
            RegisterFunction("html_decode", (Func<string, string>)HtmlDecode);
            RegisterFunction("json", (Func<Scriban.TemplateContext, object, object>)Json);
            RegisterFunction("html_strip", (Func<Scriban.TemplateContext, string, string>)HtmlStrip);
        }
    }
}
