//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System;

namespace RepoM.Plugin.SonarCloud.ActionMenu.Context
{
    partial class SonarCloudVariables
    {
        public override void RegisterFunctions(RepoM.ActionMenu.Interface.Scriban.IContextRegistration contextRegistration)
        {
            contextRegistration = contextRegistration.CreateOrGetSubRegistration("sonarcloud");
            contextRegistration.RegisterFunction("is_favorite", (Func<string, bool>)IsFavorite);
        }
    }
}
