//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System;

namespace RepoM.Plugin.AzureDevOps.ActionMenu.Context
{
    partial class AzureDevopsVariables
    {
        public override void RegisterFunctions(RepoM.ActionMenu.Interface.Scriban.IContextRegistration contextRegistration)
        {
            contextRegistration = contextRegistration.CreateOrGetSubRegistration("azure_devops");
            contextRegistration.RegisterFunction("prs", (Func<RepoM.ActionMenu.Interface.ActionMenuFactory.IActionMenuGenerationContext, string, System.Collections.IEnumerable>)GetPullRequests);
        }
    }
}
